/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TokenRouteImport } from './routes/token'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DocsUploadTokenRouteImport } from './routes/docs-upload.$token'
import { Route as DashboardTokensRouteImport } from './routes/dashboard.tokens'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardRecruitersRouteImport } from './routes/dashboard.recruiters'
import { Route as DashboardProcessesRouteImport } from './routes/dashboard.processes'
import { Route as DashboardMeetingsRouteImport } from './routes/dashboard.meetings'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard.documents'
import { Route as AssessmentTokenRouteImport } from './routes/assessment.$token'
import { Route as DashboardCandidatesIndexRouteImport } from './routes/dashboard.candidates.index'
import { Route as DashboardCandidatesIdRouteImport } from './routes/dashboard.candidates.$id'

const TokenRoute = TokenRouteImport.update({
  id: '/token',
  path: '/token',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DocsUploadTokenRoute = DocsUploadTokenRouteImport.update({
  id: '/docs-upload/$token',
  path: '/docs-upload/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTokensRoute = DashboardTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRecruitersRoute = DashboardRecruitersRouteImport.update({
  id: '/recruiters',
  path: '/recruiters',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProcessesRoute = DashboardProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMeetingsRoute = DashboardMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const AssessmentTokenRoute = AssessmentTokenRouteImport.update({
  id: '/assessment/$token',
  path: '/assessment/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCandidatesIndexRoute =
  DashboardCandidatesIndexRouteImport.update({
    id: '/candidates/',
    path: '/candidates/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardCandidatesIdRoute = DashboardCandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/token': typeof TokenRoute
  '/assessment/$token': typeof AssessmentTokenRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/processes': typeof DashboardProcessesRoute
  '/dashboard/recruiters': typeof DashboardRecruitersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/docs-upload/$token': typeof DocsUploadTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/candidates/$id': typeof DashboardCandidatesIdRoute
  '/dashboard/candidates/': typeof DashboardCandidatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/token': typeof TokenRoute
  '/assessment/$token': typeof AssessmentTokenRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/processes': typeof DashboardProcessesRoute
  '/dashboard/recruiters': typeof DashboardRecruitersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/docs-upload/$token': typeof DocsUploadTokenRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/candidates/$id': typeof DashboardCandidatesIdRoute
  '/dashboard/candidates': typeof DashboardCandidatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/token': typeof TokenRoute
  '/assessment/$token': typeof AssessmentTokenRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/meetings': typeof DashboardMeetingsRoute
  '/dashboard/processes': typeof DashboardProcessesRoute
  '/dashboard/recruiters': typeof DashboardRecruitersRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/tokens': typeof DashboardTokensRoute
  '/docs-upload/$token': typeof DocsUploadTokenRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/candidates/$id': typeof DashboardCandidatesIdRoute
  '/dashboard/candidates/': typeof DashboardCandidatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/token'
    | '/assessment/$token'
    | '/dashboard/documents'
    | '/dashboard/meetings'
    | '/dashboard/processes'
    | '/dashboard/recruiters'
    | '/dashboard/settings'
    | '/dashboard/tokens'
    | '/docs-upload/$token'
    | '/dashboard/'
    | '/dashboard/candidates/$id'
    | '/dashboard/candidates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/token'
    | '/assessment/$token'
    | '/dashboard/documents'
    | '/dashboard/meetings'
    | '/dashboard/processes'
    | '/dashboard/recruiters'
    | '/dashboard/settings'
    | '/dashboard/tokens'
    | '/docs-upload/$token'
    | '/dashboard'
    | '/dashboard/candidates/$id'
    | '/dashboard/candidates'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/token'
    | '/assessment/$token'
    | '/dashboard/documents'
    | '/dashboard/meetings'
    | '/dashboard/processes'
    | '/dashboard/recruiters'
    | '/dashboard/settings'
    | '/dashboard/tokens'
    | '/docs-upload/$token'
    | '/dashboard/'
    | '/dashboard/candidates/$id'
    | '/dashboard/candidates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  TokenRoute: typeof TokenRoute
  AssessmentTokenRoute: typeof AssessmentTokenRoute
  DocsUploadTokenRoute: typeof DocsUploadTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/token': {
      id: '/token'
      path: '/token'
      fullPath: '/token'
      preLoaderRoute: typeof TokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/docs-upload/$token': {
      id: '/docs-upload/$token'
      path: '/docs-upload/$token'
      fullPath: '/docs-upload/$token'
      preLoaderRoute: typeof DocsUploadTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tokens': {
      id: '/dashboard/tokens'
      path: '/tokens'
      fullPath: '/dashboard/tokens'
      preLoaderRoute: typeof DashboardTokensRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/recruiters': {
      id: '/dashboard/recruiters'
      path: '/recruiters'
      fullPath: '/dashboard/recruiters'
      preLoaderRoute: typeof DashboardRecruitersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/processes': {
      id: '/dashboard/processes'
      path: '/processes'
      fullPath: '/dashboard/processes'
      preLoaderRoute: typeof DashboardProcessesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/meetings': {
      id: '/dashboard/meetings'
      path: '/meetings'
      fullPath: '/dashboard/meetings'
      preLoaderRoute: typeof DashboardMeetingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/assessment/$token': {
      id: '/assessment/$token'
      path: '/assessment/$token'
      fullPath: '/assessment/$token'
      preLoaderRoute: typeof AssessmentTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/candidates/': {
      id: '/dashboard/candidates/'
      path: '/candidates'
      fullPath: '/dashboard/candidates/'
      preLoaderRoute: typeof DashboardCandidatesIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/candidates/$id': {
      id: '/dashboard/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/dashboard/candidates/$id'
      preLoaderRoute: typeof DashboardCandidatesIdRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardMeetingsRoute: typeof DashboardMeetingsRoute
  DashboardProcessesRoute: typeof DashboardProcessesRoute
  DashboardRecruitersRoute: typeof DashboardRecruitersRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardTokensRoute: typeof DashboardTokensRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardCandidatesIdRoute: typeof DashboardCandidatesIdRoute
  DashboardCandidatesIndexRoute: typeof DashboardCandidatesIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardMeetingsRoute: DashboardMeetingsRoute,
  DashboardProcessesRoute: DashboardProcessesRoute,
  DashboardRecruitersRoute: DashboardRecruitersRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardTokensRoute: DashboardTokensRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardCandidatesIdRoute: DashboardCandidatesIdRoute,
  DashboardCandidatesIndexRoute: DashboardCandidatesIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  TokenRoute: TokenRoute,
  AssessmentTokenRoute: AssessmentTokenRoute,
  DocsUploadTokenRoute: DocsUploadTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
