REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.create_recruiter(TEXT, TEXT, TEXT, TEXT) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.delete_recruiter(UUID) FROM PUBLIC;
REVOKE EXECUTE ON FUNCTION public.generate_token(INT) FROM PUBLIC;